# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.filesystem
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='T\xedtulo')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
                ('banner_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=helpers.filesystem.RandomFileName('news/'), verbose_name='Imagen principal')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('more_info_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Texto del bot\xf3n de info')),
                ('more_info_url', models.TextField(blank=True, null=True, verbose_name='URL con m\xe1s informaci\xf3n')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
