# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:31
from __future__ import unicode_literals


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid

import helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF/CIF')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n corta')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Tel\xe9fono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Direcci\xf3n')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=helpers.RandomFileName('entities/'), verbose_name='Imagen de perfil')),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('bonification_percent', models.FloatField(default=0, verbose_name='Porcentaje de bonificaci\xf3n')),
                ('max_percent_payment', models.FloatField(default=0, verbose_name='M\xe1ximo porcentaje de pago aceptado')),
                ('num_workers', models.IntegerField(default=0, verbose_name='N\xfamero de trabajadores')),
                ('legal_form', models.TextField(blank=True, null=True, verbose_name='Formulario legal')),
                ('facebook_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='P\xe1gina de Facebook')),
                ('webpage_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='P\xe1gina web')),
                ('twitter_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de Twitter')),
                ('telegram_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Canal de Telegram')),
                ('instagram_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de Instagram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registered'],
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
    ]
