# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Longitud'),
        ),
    ]
