# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20170926_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color de etiqueta (c\xf3digo hexadecimal)')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Categor\xeda',
                'verbose_name_plural': 'Categor\xedas',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='categories',
            field=models.ManyToManyField(blank=True, to='currency.Category', verbose_name='Categor\xedas'),
        ),
    ]
