# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0003_auto_20170927_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0, verbose_name='Saldo actual')),
                ('last_transaction', models.DateTimeField(blank=True, null=True, verbose_name='\xdaltima transacci\xf3n')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'verbose_name': 'Monedero',
                'verbose_name_plural': 'Monederos',
            },
        ),
    ]
