# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0, verbose_name='Cantidad')),
                ('concept', models.TextField(blank=True, null=True, verbose_name='Concepto')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='\xdaltima transacci\xf3n')),
                ('status', models.CharField(choices=[('processed', 'Procesada'), ('cancelled', 'Cancelada'), ('pending', 'Pendiente')], default='pending', max_length=20, verbose_name='Estado')),
                ('tax_processed', models.BooleanField(default=False, verbose_name='Impuestos procesados')),
                ('made_byadmin', models.BooleanField(default=False, verbose_name='Realizada por admin')),
                ('is_bonification', models.BooleanField(default=False, verbose_name='Bonificaci\xf3n')),
                ('is_euro_purchase', models.BooleanField(default=False, verbose_name='Compra de euros')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios adicionales')),
                ('rel_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.Transaction')),
                ('wallet_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='currency.Wallet')),
                ('wallet_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='currency.Wallet')),
            ],
        ),
    ]
