# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 14:42
from __future__ import unicode_literals

import helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0006_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF/CIF')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('surname', models.TextField(blank=True, null=True, verbose_name='Direcci\xf3n')),
                ('profile_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=helpers.RandomFileName('profiles/'), verbose_name='Imagen de perfil')),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registered'],
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
