# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:09
from __future__ import unicode_literals

import currency.helpers
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='banner_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=currency.helpers.RandomFileName('offers/'), verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='currency.Entity'),
        ),
    ]
