# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_person_fav_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fav_entities',
            field=models.ManyToManyField(blank=True, to='currency.Entity', verbose_name='Favoritos'),
        ),
    ]
