# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_auto_20171011_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='entity',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
