# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 13:24
from __future__ import unicode_literals

import currency.helpers
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0013_auto_20180105_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='T\xedtulo')),
            ],
            options={
                'verbose_name': 'Galer\xeda',
                'verbose_name_plural': 'Galer\xedas',
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='T\xedtulo')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=currency.helpers.RandomFileName('photos/'))),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.Gallery')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='gallery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.Gallery'),
        ),
    ]
