# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0014_auto_20180118_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.Gallery'),
        ),
    ]
