# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0015_auto_20180118_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.Gallery'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='currency.Gallery'),
        ),
    ]
