# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 12:39
from __future__ import unicode_literals

from django.db import migrations

def create_entity_group(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Entity = apps.get_model('currency', 'Entity')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    content_type = ContentType.objects.get(app_label='currency', model='Entity')
    permission = Permission.objects.create(codename='can_manage_entity',
                                           name='Can manage its entity',
                                           content_type=content_type)

    entity_group, created = Group.objects.get_or_create(name='entities')
    entity_group.permissions.add(permission)
    for entity in Entity.objects.all():
        entity.user.groups.add(entity_group)


def create_person_group(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Person = apps.get_model('currency', 'Person')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    content_type = ContentType.objects.get(app_label='currency', model='Person')
    permission = Permission.objects.create(codename='can_manage_person',
                                           name='Can manage its person',
                                           content_type=content_type)

    person_group, created = Group.objects.get_or_create(name='persons')
    person_group.permissions.add(permission)
    for entity in Person.objects.all():
        entity.user.groups.add(person_group)


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0016_auto_20180118_1757'),
    ]

    operations = [
        migrations.RunPython(create_entity_group),
        migrations.RunPython(create_person_group),
    ]
