# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 18:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0021_bonus_percent_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='bonus_percent_entity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de bonificaci\xf3n a entidades'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='bonus_percent_general',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de bonificaci\xf3n general'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='max_percent_payment',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='M\xe1ximo porcentaje de pago aceptado'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='num_workers',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='N\xfamero de trabajadores'),
        ),
    ]
