# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-17 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0024_initial_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='city',
            field=models.ForeignKey(default='mad', on_delete=django.db.models.deletion.CASCADE, to='currency.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.ForeignKey(default='mad', on_delete=django.db.models.deletion.CASCADE, to='currency.City'),
            preserve_default=False,
        ),
    ]
