# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-11 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0025_accounts_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de expiraci\xf3n'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_guest_account',
            field=models.BooleanField(default=False, verbose_name='Es usuario invitado'),
        ),
    ]
