# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-12 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0026_guest_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegisteredUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.Entity', verbose_name='Entidad')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.Person', verbose_name='Consumidora')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Categor\xeda',
                'verbose_name_plural': 'Categor\xedas',
            },
        ),
    ]
