# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-12 14:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0027_preregistereduser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preregistereduser',
            options={'ordering': ['email'], 'verbose_name': 'Prerregistro', 'verbose_name_plural': 'Prerregistros'},
        ),
        migrations.AddField(
            model_name='preregistereduser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
