# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-12 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0028_preregister_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name'], 'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AddField(
            model_name='entity',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Oculta'),
        ),
        migrations.AddField(
            model_name='entity',
            name='inactive',
            field=models.BooleanField(default=False, verbose_name='Inactiva'),
        ),
        migrations.AlterField(
            model_name='preregistereduser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preregister', to=settings.AUTH_USER_MODEL),
        ),
    ]
