# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-10-21 10:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0029_hidden_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='inactive',
            field=models.BooleanField(default=False, verbose_name='Inactiva'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='max_percent_payment',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='M\xe1ximo porcentaje de pago aceptado'),
        ),
    ]
