# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-11-28 10:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0030_auto_20220328_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='max_percent_payment',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='M\xe1ximo porcentaje de pago aceptado'),
        ),
    ]
