# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-01-26 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0031_entity_max_percent_payment_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistereduser',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email preregistro enviado'),
        ),
    ]
