# Generated by Django 3.2.18 on 2023-03-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0033_add_ondelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de socia'),
        ),
        migrations.AddField(
            model_name='person',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de socia'),
        ),
    ]
