# Generated by Django 3.2.18 on 2023-03-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0034_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_intercoop',
            field=models.BooleanField(default=False, verbose_name='Es socia de intercooperación'),
        ),
    ]
