# Generated by Django 3.2.18 on 2023-05-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0035_person_is_intercoop'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='balance_detail',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Informe balance'),
        ),
    ]
