# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0, verbose_name='Cantidad')),
                ('concept', models.TextField(blank=True, null=True, verbose_name='Concepto')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('status', models.CharField(choices=[('processed', 'Procesada'), ('cancelled', 'Cancelada'), ('pending', 'Pendiente')], default='pending', max_length=20, verbose_name='Estado')),
                ('tax_processed', models.BooleanField(default=False, verbose_name='Impuestos procesados')),
                ('made_byadmin', models.BooleanField(default=False, verbose_name='Realizada por admin')),
                ('is_bonification', models.BooleanField(default=False, verbose_name='Bonificaci\xf3n')),
                ('is_euro_purchase', models.BooleanField(default=False, verbose_name='Compra de euros')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios adicionales')),
                ('rel_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallets.Transaction')),
            ],
            options={
                'ordering': ['timestamp'],
                'verbose_name': 'Transacci\xf3n',
                'verbose_name_plural': 'Transacciones',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0, verbose_name='Saldo actual')),
                ('last_transaction', models.DateTimeField(blank=True, null=True, verbose_name='\xdaltima transacci\xf3n')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'verbose_name': 'Monedero',
                'verbose_name_plural': 'Monederos',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='wallets.Wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='wallets.Wallet'),
        ),
    ]
