# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0016_auto_20180118_1757'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0002_remove_transaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('processed', models.DateTimeField(verbose_name='Timestamp procesado')),
                ('status', models.CharField(choices=[('accepted', 'Aceptado'), ('cancelled', 'Cancelado'), ('pending', 'Pendiente')], max_length=8)),
                ('total_amount', models.FloatField(default=0, verbose_name='Importe total')),
                ('currency_amount', models.FloatField(default=0, verbose_name='Cantidad en boniatos')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
