# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_auto_20180201_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('amount', models.FloatField(default=0, verbose_name='Cantidad')),
                ('concept', models.TextField(blank=True, null=True, verbose_name='Concepto')),
                ('made_byadmin', models.BooleanField(default=False, verbose_name='Realizada por admin')),
                ('is_bonification', models.BooleanField(default=False, verbose_name='Bonificaci\xf3n')),
                ('is_euro_purchase', models.BooleanField(default=False, verbose_name='Compra de euros')),
                ('current_balance', models.FloatField(default=0, verbose_name='Saldo')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_logs', to='wallets.Wallet')),
            ],
            options={
                'ordering': ['timestamp'],
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
    ]
