# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_auto_20180202_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
    ]
