# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_auto_20180202_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('accepted', 'Aceptado'), ('cancelled', 'Cancelado'), ('pending', 'Pendiente')], max_length=10),
        ),
    ]
