# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_payment_status_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='pin_code',
            field=models.CharField(max_length=100, null=True, verbose_name='C\xf3digo PIN (hasheado)'),
        ),
    ]
