# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 13:05
from __future__ import unicode_literals

from django.db import migrations


def create_initial_wallet_types(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Wallet = apps.get_model('wallets', 'Wallet')
    WalletType = apps.get_model('wallets', 'WalletType')

    default_type = WalletType.objects.create(id='default', name='Normal', credit_limit=0, unlimited=False)
    debit_type = WalletType.objects.create(id='debit', name='Débito', credit_limit=0, unlimited=True)

    # set all wallets to the default type
    for wallet in Wallet.objects.all():
        wallet.type = default_type
        wallet.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_wallet_types'),
    ]

    operations = [
        migrations.RunPython(create_initial_wallet_types),
    ]


