# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 13:05
from __future__ import unicode_literals

from django.db import migrations


def create_initial_wallet_type(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Entity = apps.get_model('currency', 'entity')
    Wallet = apps.get_model('wallets', 'Wallet')
    WalletType = apps.get_model('wallets', 'WalletType')

    entity_type = WalletType.objects.create(id='entity', name='Entidad', credit_limit=500, unlimited=False)
    # set all entity wallets to the new type
    for entity in Entity.objects.all():
        for wallet in Wallet.objects.filter(user=entity.user):
            wallet.type = entity_type
            wallet.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_initial_wallet_types'),
    ]

    operations = [
        migrations.RunPython(create_initial_wallet_type),
    ]


