# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 13:05
from __future__ import unicode_literals

from django.db import migrations


def create_debit_wallet(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Wallet = apps.get_model('wallets', 'Wallet')
    WalletType = apps.get_model('wallets', 'WalletType')

    debit_type = WalletType.objects.get(id='debit')
    #Create new wallet with debit type
    wallet = Wallet.objects.create(type=debit_type)


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0013_wallet_no_user'),
    ]

    operations = [
        migrations.RunPython(create_debit_wallet),
    ]


