# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-14 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0014_debit_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='concept',
            field=models.TextField(blank=True, null=True, verbose_name='Concepto (opcional)'),
        ),
    ]
