# Generated by Django 3.2.18 on 2023-03-23 18:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0035_person_is_intercoop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('benefit_for_entities', models.TextField(blank=True, null=True, verbose_name='Ventajas para entidades')),
                ('benefit_for_members', models.TextField(blank=True, null=True, verbose_name='Ventajas para socias')),
                ('includes_intercoop_members', models.BooleanField(default=False, verbose_name='Incluye socias Intercoop')),
                ('in_person', models.BooleanField(default=True, verbose_name='Solicitud física')),
                ('online', models.BooleanField(default=True, verbose_name='Solicitud online')),
                ('discount_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de descuento')),
                ('discount_link', models.URLField(blank=True, max_length=100, null=True, verbose_name='Link de descuento')),
                ('discount_link_text', models.CharField(blank=True, default='Ir al descuento', max_length=50, null=True, verbose_name='Texto del botón del link de descuento')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benefit', to='currency.entity')),
            ],
            options={
                'verbose_name': 'Ventaja',
                'verbose_name_plural': 'Ventajas',
                'ordering': ['-published_date'],
            },
        ),
    ]
