# Generated by Django 3.2.18 on 2023-03-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_add_benefit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='discount_link',
        ),
        migrations.AddField(
            model_name='benefit',
            name='discount_link_entities',
            field=models.URLField(blank=True, null=True, verbose_name='Link de descuento para entidades'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='discount_link_members',
            field=models.URLField(blank=True, null=True, verbose_name='Link de descuento para socias'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='discount_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Código de descuento'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='discount_link_text',
            field=models.CharField(blank=True, default='Solicitar descuento', max_length=100, null=True, verbose_name='Texto del botón del link de descuento'),
        ),
    ]
